application:
#  name: skshu-api-client-shuapp
  name: spring-cloud-SMS
  version: 1.0
spring:
  application:
    name: ${application.name}
  profiles:
    active: dev  #dev和test都是对应nacos上的${spring.application.name}-dev-${application.version}上，


#logging:
#  config: classpath:logback-setting.xml
#mybatis-plus:
#  configuration:
#    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
#    map-underscore-to-camel-case: false